"""
bdf2c.py - convert Marlin BDF bitmap fonts (public domain) to C arrays for tft_display.c

Usage: python tools/bdf2c.py <marlin buildroot/share/fonts dir> > Src/tft_fonts.h

Each font is converted for a given character set into fixed size cells.
The cell height is cropped to the rows actually used by that character set.
Row data: bytes_per_row bytes per row, MSB = leftmost pixel.
"""

import os
import sys

FONTS = [
    # (C name, BDF file, character set)
    ("font_s", "marlin-12x24.bdf", "".join(chr(c) for c in range(32, 127))),
    ("font_m", "marlin-16x32.bdf", " $%/-.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"),
    ("font_l", "marlin-24x48.bdf", " -.0123456789XYZ"),
]


def parse_bdf(path):
    glyphs = {}
    ascent = descent = 0
    with open(path, encoding="latin-1") as f:
        lines = [l.rstrip("\n") for l in f]
    i = 0
    while i < len(lines):
        l = lines[i]
        if l.startswith("FONT_ASCENT"):
            ascent = int(l.split()[1])
        elif l.startswith("FONT_DESCENT"):
            descent = int(l.split()[1])
        elif l.startswith("STARTCHAR"):
            enc = dw = None
            bbx = (0, 0, 0, 0)
            rows = []
            i += 1
            while not lines[i].startswith("ENDCHAR"):
                p = lines[i].split()
                if p[0] == "ENCODING":
                    enc = int(p[1])
                elif p[0] == "DWIDTH":
                    dw = int(p[1])
                elif p[0] == "BBX":
                    bbx = tuple(int(v) for v in p[1:5])
                elif p[0] == "BITMAP":
                    i += 1
                    while not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16) if lines[i] else 0)
                        rows_hexlen = len(lines[i])
                        i += 1
                    glyphs[enc] = (dw, bbx, rows, len(lines[i - 1]) if rows else 0)
                    break
                i += 1
            if enc is not None and enc not in glyphs:
                glyphs[enc] = (dw, bbx, rows, 0)
        i += 1
    return glyphs, ascent, descent


def render(glyph, ascent, cell_w, cell_h):
    dw, (w, h, xo, yo), rows, hexlen = glyph
    bmp = [[0] * cell_w for _ in range(cell_h)]
    bits = hexlen * 4
    top = ascent - (yo + h)
    for r, val in enumerate(rows):
        y = top + r
        for c in range(w):
            x = xo + c
            if 0 <= y < cell_h and 0 <= x < cell_w and (val >> (bits - 1 - c)) & 1:
                bmp[y][x] = 1
    return bmp


def main():
    src = sys.argv[1]
    out = ["// Generated by tools/bdf2c.py from Marlin BDF fonts (public domain), do not edit.", "",
           "#pragma once", "", "#include <stdint.h>", "",
           "typedef struct {", "    uint8_t width;", "    uint8_t height;", "    uint8_t bytes_per_row;",
           "    const char *chars;", "    const uint8_t *data;", "} tft_font_t;", ""]
    for name, file, charset in FONTS:
        glyphs, ascent, descent = parse_bdf(os.path.join(src, file))
        cell_w = max(glyphs[ord(c)][0] for c in charset)
        full_h = ascent + descent
        bmps = [render(glyphs[ord(c)], ascent, cell_w, full_h) for c in charset]
        used = [y for b in bmps for y in range(full_h) if any(b[y])]
        y0, y1 = min(used), max(used)
        y0 = max(0, y0 - 1)
        y1 = min(full_h - 1, y1 + 1)
        cell_h = y1 - y0 + 1
        bpr = (cell_w + 7) // 8
        data = []
        for b in bmps:
            for y in range(y0, y1 + 1):
                v = 0
                for x in range(bpr * 8):
                    v = (v << 1) | (b[y][x] if x < cell_w else 0)
                data += [(v >> (8 * (bpr - 1 - k))) & 0xFF for k in range(bpr)]
        esc = charset.replace("\\", "\\\\").replace("\"", "\\\"")
        out.append(f"static const uint8_t {name}_data[] = {{ // {cell_w}x{cell_h}, {len(charset)} glyphs")
        per = bpr * cell_h
        for gi, c in enumerate(charset):
            chunk = data[gi * per:(gi + 1) * per]
            out.append("    " + ", ".join(f"0x{v:02X}" for v in chunk) + f", // '{c}'" if c != "\\" else
                       "    " + ", ".join(f"0x{v:02X}" for v in chunk) + ", // backslash")
        out.append("};")
        out.append(f"static const tft_font_t {name} = {{ {cell_w}, {cell_h}, {bpr}, \"{esc}\", {name}_data }};")
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
