"""
ttf2c.py - render anti-aliased fonts and icons for tft_display.c

Usage: python tools/ttf2c.py > Src/tft_aafonts.h
Needs Pillow (pip install pillow).

Sources in tools/fonts/:
  Roboto.ttf          Roboto variable font, SIL Open Font License (OFL-Roboto.txt)
  tabler-icons.ttf    Tabler Icons webfont, MIT license (LICENSE-tabler.txt)

Glyph format: 4 bits per pixel (alpha, 0 = background, 15 = foreground), two pixels
per byte with the left pixel in the high nibble, each row padded to whole bytes.
The bitmap of a glyph is as wide as its advance and as high as the font, so drawing
glyph after glyph covers the background completely.
"""

import os
from PIL import Image, ImageDraw, ImageFont

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")
ROBOTO = os.path.join(DIR, "Roboto.ttf")
TABLER = os.path.join(DIR, "tabler-icons.ttf")

ASCII = "".join(chr(c) for c in range(32, 127))

FONTS = [
    # (C name, weight, pixel size, character set)
    ("aa_small", "Regular", 13, " -.0123456789Mmm"),
    ("aa_label", "Medium", 16, ASCII),
    ("aa_state", "Bold", 19, " -.:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"),
    ("aa_axis", "Bold", 36, " XYZ"),
    ("aa_dro", "Bold", 46, " -.0123456789"),
]

# Icons are addressed by a letter, see the ICON_ defines in the output.
ICONS = [
    ("menu", "m", 0xEC42),
    ("home", "h", 0xEAC1),
    ("unlock", "u", 0xEAE1),
    ("crosshair", "x", 0xEC3E),
    ("zero_z", "z", 0xEC88),
    ("pause", "p", 0xED45),
    ("play", "r", 0xED46),
    ("flame", "f", 0xEC2C),
    ("file", "d", 0xEAA4),
    ("check", "c", 0xEA67),
    ("alert", "a", 0xEA06),
    ("stop", "s", 0xED4A),
    ("clock", "w", 0xEA70),
    ("door", "o", 0xEF4E),
    ("tool", "t", 0xEB40),
    ("sleep", "q", 0xF228),
    ("search", "k", 0xEB1C),
    ("back", "b", 0xEA19),
    ("axis_x", "i", 0xEF45),
    ("axis_y", "j", 0xEF46),
    ("zero_all", "l", 0xF02A),
    ("settings", "g", 0xEB20),
    ("sd_card", "e", 0xF384),
    ("touch", "n", 0xEE94),
    ("mode", "v", 0xEB31),
]

ICON_SETS = [
    # (C name, pixel size)
    ("aa_icon_s", 20),
    ("aa_icon_l", 28),
]

SS = 4  # supersampling for the icons


def quantize(img):
    return [[(img.getpixel((x, y)) * 15 + 127) // 255 for x in range(img.width)] for y in range(img.height)]


def render_text_font(weight, size, chars):
    font = ImageFont.truetype(ROBOTO, size)
    font.set_variation_by_name(weight)
    ascent, descent = font.getmetrics()
    glyphs = []
    for c in chars:
        adv = max(1, round(font.getlength(c)))
        img = Image.new("L", (adv, ascent + descent), 0)
        ImageDraw.Draw(img).text((0, ascent), c, font=font, fill=255, anchor="ls")
        glyphs.append((c, quantize(img)))
    # crop to the rows used by this character set
    rows = [y for _, g in glyphs for y, r in enumerate(g) if any(r)]
    top, bottom = min(rows), max(rows) + 1
    return [(c, [r for r in g[top:bottom]]) for c, g in glyphs], bottom - top


def render_icon(code, size):
    font = ImageFont.truetype(TABLER, size * SS)
    big = Image.new("L", (size * SS, size * SS), 0)
    d = ImageDraw.Draw(big)
    ch = chr(code)
    l, t, r, b = d.textbbox((0, 0), ch, font=font)
    d.text(((size * SS - (r - l)) / 2 - l, (size * SS - (b - t)) / 2 - t), ch, font=font, fill=255)
    return quantize(big.resize((size, size), Image.LANCZOS))


def pack(rows):
    out = []
    for r in rows:
        if len(r) & 1:
            r = r + [0]
        for i in range(0, len(r), 2):
            out.append((r[i] << 4) | r[i + 1])
    return out


def c_char(c):
    return "\\\\" if c == "\\" else ('\\"' if c == '"' else c)


def emit(name, glyphs, height, cell_w):
    data, table = [], []
    for c, rows in glyphs:
        table.append((len(rows[0]), len(data), c))
        data.extend(pack(rows))
    print(f"static const uint8_t {name}_data[] = {{ // height {height}, {len(glyphs)} glyphs, {len(data)} bytes")
    for i in range(0, len(data), 24):
        print("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 24]) + ",")
    print("};\n")
    print(f"static const aa_glyph_t {name}_glyphs[] = {{")
    for w, off, c in table:
        print(f"    {{ {w}, {off} }}, // '{c}'" if c.isprintable() else f"    {{ {w}, {off} }},")
    print("};\n")
    chars = "".join(c_char(c) for _, _, c in table)
    print(f'static const aa_font_t {name} = {{ {height}, {cell_w}, "{chars}", {name}_glyphs, {name}_data }};\n')


def main():
    print("// Generated by tools/ttf2c.py from Roboto (SIL OFL 1.1) and Tabler Icons (MIT), do not edit.\n")
    print("#pragma once\n")
    print("#include <stdint.h>\n")
    print("typedef struct {\n    uint8_t width;\n    uint16_t offset;\n} aa_glyph_t;\n")
    print("typedef struct {\n    uint8_t height;\n    uint8_t cell_w;     // widest digit, for fields with fixed character cells\n"
          "    const char *chars;\n    const aa_glyph_t *glyphs;\n    const uint8_t *data;\n} aa_font_t;\n")

    for name, letter, _ in ICONS:
        print(f"#define ICON_{name.upper():<10} '{letter}'")
    print()

    # dedupe characters, keep order
    for name, weight, size, chars in FONTS:
        chars = "".join(dict.fromkeys(chars))
        glyphs, height = render_text_font(weight, size, chars)
        digits = [len(g[0]) for c, g in glyphs if c.isdigit()]
        emit(name, glyphs, height, max(digits) if digits else max(len(g[0]) for _, g in glyphs))

    for name, size in ICON_SETS:
        glyphs = [(letter, render_icon(code, size)) for _, letter, code in ICONS]
        emit(name, glyphs, size, size)


if __name__ == "__main__":
    main()
